#!/bin/bash
echo " Enter the year "
read year
if (( $year % 400 == 0   || ( $year % 4 == 0   &&  $year % 100 != 0 ) ))
then
        echo "The $year is leap year "
else
        echo "The $year is not leap year "
fi
